version: '{build}-{branch}'
os: Default Azure
platform:
  - x64
init:
  - ps: |
      mkdir C:\Users\appveyor\.vagrant.d | Out-Null
  - ps: |
      mkdir C:\downloads | Out-Null
      cd C:\downloads
      [Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'
      Start-FileDownload "https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1.msi"
      Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant_1.8.1.msi /qb TARGETDIR=C:\Vagrant" -Wait
      Start-FileDownload "http://download.virtualbox.org/virtualbox/5.0.14/VirtualBox-5.0.14-105127-Win.exe"
      Start-Process -FilePath "VirtualBox-5.0.14-105127-Win.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox" -Wait
      cd $env:APPVEYOR_BUILD_FOLDER
install:
  - set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
  - vagrant -v
  - VBoxManage -v
  - ssh -V
  - ipconfig /all
build_script:
  - ps: Test-NetConnection google.com -Port 80
  - vagrant up
  - vagrant ssh -c "echo 'hello world!'"
test: off
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
